# -*- coding: utf-8 -*-
"""Preyecto_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13RBk6L52XB30YCDSYQNSfaXJjh8pWmDi
"""

#Importamos las librerías necesarias

import os,shutil
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, GlobalAveragePooling2D
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.models import Model
import random

#import streamlit as st
from PIL import Image
import matplotlib.pyplot as plt

#Descargamos los datos sin filtros

!curl -O https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip

#Descomprimir

!unzip -q kagglecatsanddogs_5340.zip
!ls

#Comprobamos que se han creado las subcarpetas correctamente con el comando ls

!ls PetImages

#Eliminar datos corruptos

num_skipped = 0
for folder_name in ("Cat", "Dog"):
    folder_path = os.path.join("PetImages", folder_name)
    for fname in os.listdir(folder_path):
        fpath = os.path.join(folder_path, fname)
        try:
            with open(fpath, "rb") as fobj:  #with open() para cerrar automáticamente el archivo.
                is_jfif = tf.compat.as_bytes("JFIF") in fobj.read(10)
            if not is_jfif:
                num_skipped += 1
                os.remove(fpath)
        except Exception as e:
            print(f"⚠️ Error con {fpath}: {e}")
            num_skipped += 1
            os.remove(fpath)

print("Deleted %d images" % num_skipped)

# Definir directorios
data_dir = "PetImages"
train_dir = os.path.join(data_dir, "train")
validation_dir = os.path.join(data_dir, "validation")

# Cargar MobileNetV2 sin la capa de clasificación
base_model = MobileNetV2(weights="imagenet", include_top=False, input_shape=(160, 160, 3))
base_model.trainable = False  # Congelamos los pesos preentrenados

# Agregar capas personalizadas
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
predictions = Dense(1, activation='sigmoid')(x)

#Este código confirma que las carpetas necesarias están creadas

base_dir = "PetImages"
sub_dirs = ["train", "validation", "test"]

for sub in sub_dirs:
    path = os.path.join(base_dir, sub)
    os.makedirs(path, exist_ok=True)

print("Estructura de carpetas creada correctamente.")

#Este código distribuye las imágenes en train, validation y test:

base_dir = "PetImages"
categories = ["Cat", "Dog"]
split_ratio = [0.7, 0.15, 0.15]  # 70% train, 15% val, 15% test

for category in categories:
    src_folder = os.path.join(base_dir, category)
    images = [f for f in os.listdir(src_folder) if f.endswith(("jpg", "png", "jpeg"))]
    random.shuffle(images)

    train_split = int(len(images) * split_ratio[0])
    val_split = int(len(images) * (split_ratio[0] + split_ratio[1]))

    for i, img in enumerate(images):
        src_path = os.path.join(src_folder, img)
        if i < train_split:
            dst_folder = os.path.join(base_dir, "train", category.lower())
        elif i < val_split:
            dst_folder = os.path.join(base_dir, "validation", category.lower())
        else:
            dst_folder = os.path.join(base_dir, "test", category.lower())

        os.makedirs(dst_folder, exist_ok=True)
        shutil.move(src_path, os.path.join(dst_folder, img))

print("Imágenes organizadas correctamente en train, validation y test.")

# Crear el modelo
model = Model(inputs=base_model.input, outputs=predictions)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Generadores de imágenes
train_datagen = ImageDataGenerator(rescale=1./255, horizontal_flip=True)
val_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    train_dir, target_size=(160, 160), batch_size=32, class_mode='binary')
validation_generator = val_datagen.flow_from_directory(
    validation_dir, target_size=(160, 160), batch_size=32, class_mode='binary')

# Entrenar el modelo
epochs = 5
model.fit(train_generator, validation_data=validation_generator, epochs=epochs)

# Guardar el modelo
model.save("cat_dog_classifier.h5")

# Evaluar el modelo con el conjunto de validación
score = model.evaluate(validation_generator, verbose=0)

# Mostrar resultados
print("Validation loss:", score[0])
print("Validation accuracy:", score[1])

history=model.fit(
    train_generator,
    steps_per_epoch= 100,
    epochs= 100,
    validation_data=validation_generator,
    validation_steps= 50
)

# visualizamos los resultados como antes
# almacenamos acc, loss, val_acc y val_loss desde history
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']
# definimos epochs con rango 1 a len(acc)+1
epochs = range(1, len(acc)+1)
# creamos grafico con acc y val_acc
plt.plot(epochs, acc, 'bo', label='Training acc')
plt.plot(epochs, val_acc, 'b', label='Validation acc')
plt.title('Training and validation accuracy')
plt.legend()

plt.figure()
# creamos gráfico con loss y val_loss
plt.plot(epochs, loss, 'bo', label='Training loss')
plt.plot(epochs, val_loss, 'b', label='Validation loss')
plt.title('Training and validation loss')
plt.legend()
# mostramos gráfico
plt.show()

#Comprobar Overfitting
train_loss, train_accuracy = model.evaluate(train_generator, verbose=0)
val_loss, val_accuracy = model.evaluate(validation_generator, verbose=0)

print(f"Train Loss: {train_loss:.4f} - Train Accuracy: {train_accuracy:.4%}")
print(f"Validation Loss: {val_loss:.4f} - Validation Accuracy: {val_accuracy:.4%}")

"""Hay un ligero overfitting, pero no es grave."""